### ISSUE TITLE
css滚动条样式隐藏设置

### ISSUE THREAD

**Issue by yihan12** [yihan12/Blog#28]
```css
/* 全局滚动条样式 */
::-webkit-scrollbar {
  width: 0px; /* 纵向滚动条*/
  height: 0px; /* 横向滚动条 */
  background-color: #fff;
}

/*定义滚动条轨道 内阴影*/
::-webkit-scrollbar-track {
  box-shadow: inset 0 0 6px rgba(0, 0, 0, 0);
  background-color: transparent;
}

/*定义滑块 内阴影*/
::-webkit-scrollbar-thumb {
  box-shadow: inset 0 0 6px rgba(0, 0, 0, 0);
  background-color: transparent;
  border-radius: 10px;
}
```
